# Generated by Django 2.0.5 on 2018-09-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
